### ISSUE TITLE
print the routes of mincost solution

### ISSUE THREAD

**Issue by mrprajesh** [MarwanAbdelatti/GA_VRP_GPU#1]
Thanks for providing the source @MarwanAbdelatti. 
We are in process of comparing our CVRP results with your research work.
Is there a way to print the routes of best solution? or could you point me how should we perform? At least, you could refer to lines in `.py` file where we should modify.  Thanks a lot.

Kind regards,
Rajesh

**Comment by MarwanAbdelatti** [comment]
Hi Rajesh,
Thanks so much for reaching out. I understood that you want to plot the routes to visualize the solution. Actually I didn't do this in my algorithm but the final solution is printed out on the screen. So, what I'd suggest is to take the final solution, divide it into sub-tours based on the depot node delimiters, and use the `matplotlib` in python to plot the nodes first then the lines connecting them.

You may define this plotting function and call it after printing the best solution (i.e., after line # 914).

I hope this answers your question.

Best,
Marwan.

**Comment by mrprajesh** [comment]
> Hi Rajesh,
> Thanks so much for reaching out. I understood that you want to plot the routes to visualize the solution. Actually I didn't do this in my algorithm but the final solution is printed out on the screen. So, what I'd suggest is to take the final solution, divide it into sub-tours based on the depot node delimiters, and use the matplotlib in python to plot the nodes first then the lines connecting them.

Sure, we wanted to print output in a [specified format](http://vrp.galgos.inf.puc-rio.br/media/com_vrp/instances/X/X-n101-k25.sol). Visualising would be a good thing to do next.
> You may define this plotting function and call it after printing the best solution (i.e., after line # 914). I'd also suggest to take a look at out work that uses Reinforcement Learning in tuning the algorithm in the following link:
> Paper: https://www.researchgate.net/profile/Marwan-Abdelatti/publication/351874169_Using_Reinforcement_Learning_for_Tuning_Genetic_Algorithms/links/60ae41d5a6fdcc647edc5180/Using-Reinforcement-Learning-for-Tuning-Genetic-Algorithms.pdf
> 
> Code: https://github.com/J-Que/RL-GA
> 
> I hope this answers your question.

Yes, it was very helpful. Sure, we will check out RL-GA as well. Thanks.

**Comment by MarwanAbdelatti** [comment]
You are very welcome. Please don't hesitate to contact me if you have any question either about this work or about the RL-GA one.
